# Generated by Django 2.2.4 on 2021-06-24 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210403_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='main_app.User'),
        ),
    ]
